
import argparse
import sys
import os
from PIL import Image

def convert_png_to_lvgl(input_path, output_path=None, array_name=None):
    if not os.path.exists(input_path):
        print(f"Error: Input file '{input_path}' not found.")
        sys.exit(1)

    filename = os.path.basename(input_path)
    name_no_ext = os.path.splitext(filename)[0].replace(" ", "_").replace("-", "_").lower()
    
    if not array_name:
        array_name = f"img_{name_no_ext}"
        
    if not output_path:
        output_path = f"{array_name}.c"

    try:
        # Convert to RGBA
        img = Image.open(input_path).convert("RGBA")
        width, height = img.size
        print(f"Converting {filename} ({width}x{height}) to ARGB8888...")

        r, g, b, a = img.split()
        # Re-merge as BGRA (Little Endian ARGB8888)
        img_bgra = Image.merge("RGBA", (b, g, r, a))
        data = img_bgra.tobytes()

        # Create C file content
        c_lines = []
        c_lines.append(f'#include "lvgl.h"')
        c_lines.append(f'')
        c_lines.append(f'// Generated by scripts/png2lvgl.py')
        c_lines.append(f'// Source: {filename}')
        c_lines.append(f'// Format: LV_COLOR_FORMAT_ARGB8888 ({width}x{height})')
        c_lines.append(f'')
        
        c_lines.append(f'const uint8_t {array_name}_map[] = {{')
        
        hex_data = [f"0x{b:02x}" for b in data]
        for i in range(0, len(hex_data), 16):
            chunk = hex_data[i:i+16]
            c_lines.append("  " + ", ".join(chunk) + ",")
            
        c_lines.append(f'}};')
        c_lines.append(f'')
        
        c_lines.append(f'const lv_img_dsc_t {array_name} = {{')
        c_lines.append(f'  .header.cf = LV_COLOR_FORMAT_ARGB8888,')
        c_lines.append(f'  .header.w = {width},')
        c_lines.append(f'  .header.h = {height},')
        c_lines.append(f'  .data_size = {len(data)},')
        c_lines.append(f'  .data = {array_name}_map,')
        c_lines.append(f'}};')

        with open(output_path, "w") as f:
            f.write("\n".join(c_lines))
            
        print(f"Success! Output saved to: {output_path}")
        print(f"Struct name: {array_name}")
        print(f"Don't forget to declare it in your header: extern const lv_img_dsc_t {array_name};")

    except Exception as e:
        print(f"Error converting image: {e}")
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert PNG to LVGL ARGB8888 C Array")
    parser.add_argument("input", help="Path to input PNG file")
    parser.add_argument("-o", "--output", help="Path to output .c file (optional)")
    parser.add_argument("-n", "--name", help="Name of the C variable/struct (optional)")
    
    args = parser.parse_args()
    convert_png_to_lvgl(args.input, args.output, args.name)
